# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS)	+= oplus_ipv6_rto.o oplus_nwpower.o oplus_project.o
obj-$(CONFIG_NANDSWAP)		+= oplus_nandswap/
obj-$(CONFIG_OPLUS_FEATURE_UXIO_FIRST)	+= uxio_first/
obj-$(CONFIG_OPLUS_SUBSYS_SLEEP_MONITOR) 	+= oplus_subsys_sleep_monitor.o
obj-$(CONFIG_OPLUS_WAKELOCK_PROFILER) 	+= oplus_wakelock_profiler.o
