# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2018-2020 Oplus. All rights reserved.
obj-$(CONFIG_OPLUS) 	+= oplus_project.o
obj-$(CONFIG_NANDSWAP)		+= nandswap/
obj-$(CONFIG_OPLUS_FEATURE_UXIO_FIRST)	+= uxio_first/
